### Add a new subscription email
POST http://localhost/api/subscribe
Content-Type: "application/json"

{
  "email": "johndoe@gmail.com"
}

### Get all subscription emails
GET http://localhost/api/subscribe